Created react-redux.md
HiDIKI/hidiki.github.io.build pull request #10
Opened 2019-04-20 10:37 UTC by DeveloperYB

1. Added information about redux
2. Added information about flux

2019-04-20 12:32 UTC, hidekuma requested changes
- 이미지 삽입방법 관련 문서 공유합니다 [<참고링크>](https://v1.vuepress.vuejs.org/guide/assets.html#base-url)
  - 이미지는 `md_docs/.vuepress/public` 하위에 삽입
  - 잘 모르겠으면 해당 문서 참고해주세요 [예시문서](https://raw.githubusercontent.com/HiDIKI/hidiki.github.io.build/master/md_docs/java/sts-with-lombok.mdhttps://raw.githubusercontent.com/HiDIKI/hidiki.github.io.build/master/md_docs/java/sts-with-lombok.md)
- 예시 
```
<img :src="$withBase('/sts-with-lombok/lombok-error.png')" alt="lombok-error">
```

2019-04-20 15:01 UTC, DeveloperYB commented
- 이미지 삽입방법 관련 문서 참조하여 수정하였습니다.

2019-04-21 02:40 UTC, hidekuma approved these changes
굿쬽!!! 💯

2019-04-21 02:40 UTC, merged

2019-04-21 02:43 UTC, hidekuma commented
오 배포된거 봤는데 완전 잘썻네요 👍