Added ts-primitive-types.md
HiDIKI/hidiki.github.io.build pull request #43
Opened 2019-05-03 07:55 UTC by juunone

2019-05-03 14:12 UTC, hidekuma requested changes
Author 컴포넌트 빠져서 글쓴이 안나오겠는걸요??

2019-05-03 16:30 UTC, juunone reviewed
modified _success_!

2019-05-03 16:31 UTC, juunone commented
> Author 컴포넌트 빠져서 글쓴이 안나오겠는걸요??

2019-05-04 02:31 UTC, hidekuma approved these changes

2019-05-04 02:31 UTC, merged