Created asynchronous-programming.md file
HiDIKI/hidiki.github.io.build pull request #44
Opened 2019-05-04 16:23 UTC by DeveloperYB

2019-05-05 13:51 UTC, hidekuma requested changes
## 리뷰
전체적으로 베리 굿한 문서인것같은데 다 못읽었습니다. 해당 문서는 여러 챕터에 나누는건 힘들겠죠?
몇가지 View상의 개인적인 코멘트 드립니다.

## 코멘트
개인적인 견해이므로 한번 살펴보시고 반영여부 판단 부탁드립니다.
- 19~23 line: 불필요한 줄바꿈 > 리스트로 하심이 어떠신지
- 한페이지에 예시 1) 등 겹치는 ### 태그가 존재함 ##의 예시인 것을 알게끔 수정하는것은 어떨지
  - ex: ### 예시 1. Callback :부가설명
- 100,120 line등: tip,warning,danger과 같은 인포태그가 있으니 교체 요청
- 특정예시는 불필요하게 길다(10초 테스트>5초 테스트)
- 헤더가 특정 내용을 제대로 가르키지 못하는경우가 간혹있는것같아요

고생하셨습니다 :+1: :100: :1st_place_medal:

2019-05-06 06:10 UTC, taekbari commented on md_docs/javascript/asynchronous-programming.md
> +- 파일 일고, 쓰기 같은 파일시스템 작업
오타가 발견되었습니다. '읽고'로 수정 부탁드립니다~

2019-05-06 13:27 UTC, DeveloperYB commented
- 챕터별 Intro, 1,2,3,4 분기하였습니다.
- 오타 수정하였습니다.
- Tip 등 글을 조금 더 수정 및 위치를 변경하였습니다.

2019-05-06 13:38 UTC, hidekuma approved these changes
good job

2019-05-06 13:38 UTC, merged